### ISSUE TITLE
Computing the secondary structure map - ''KeyError: key "b" not found''

### ISSUE THREAD

**Issue by LV-IQ** [BioJulia/ProteinSecondaryStructures.jl#1]
Boa tarde, professor!

Ao executar os seguintes comandos: 

```
using Stride
import PDBTools
import Chemfiles

pdbfile = "system.pdb"
trajectory_file = "production_cut2.xtc"

atoms = PDBTools.readPDB(pdbfile, "protein")
trajectory = Chemfiles.Trajectory(trajectory_file)

ssmap = ss_map(atoms, trajectory) # returns a matrix
``` 
O erro devolvido ao executar a última linha é: ERROR: KeyError: key "b" not found. 

Os dois arquivos (pdb e xtc) utilizados podem ser encontrados neste drive: https://drive.google.com/drive/folders/1wfD_ovwzlLEOI-Uhe9ZYyvANOT6e0z3W?usp=sharing

**Comment by lmiq** [comment]
Deve estar funcionando agora (o stride devolve "b" em vez de "B" de vez em quando). Atualize e teste.
