### ISSUE TITLE
convert readme into docs

### ISSUE THREAD

**Issue by lmiq** [BioJulia/ProteinSecondaryStructures.jl#2]
@marcom 

I have requested the registration of version 0.1.0 of the package (in 3 days, with the new name `ProteinSecondaryStructures`. 

My students are already using this and it will be easier with the package registered and proper dependency version control.

I will be, at some point, converting the readme file to a proper Julia docs page (I'm just linking you here to let you know of the changes without disturbing Mosè in that other issue).

**Comment by marcom** [comment]
It has taken quite some time, but I think we now have a working build script for DSSP in BinaryBuilder (https://github.com/JuliaPackaging/Yggdrasil/pull/6998). I was forced to build DSSP without using the `libcifpp_jll` build, as it still has a bug on windows, so at the moment everything is built inside the DSSP `build_tarballs.jl`, linked statically, and only the `mkdssp` binary is installed. Maybe we can fix the dynamic linking and building a shared library `libdssp.so` later.

**Comment by lmiq** [comment]
Mostly done in v0.3.0

Needs polishing.
