### ISSUE TITLE
Provide DSSP and Stride binaries

### ISSUE THREAD

**Issue by lmiq** [BioJulia/ProteinSecondaryStructures.jl#3]
It has taken quite some time, but I think we now have a working build script for DSSP in BinaryBuilder (https://github.com/JuliaPackaging/Yggdrasil/pull/6998). I was forced to build DSSP without using the `libcifpp_jll` build, as it still has a bug on windows, so at the moment everything is built inside the DSSP `build_tarballs.jl`, linked statically, and only the `mkdssp` binary is installed. Maybe we can fix the dynamic linking and building a shared library `libdssp.so` later.

_Originally posted by @marcom in https://github.com/m3g/ProteinSecondaryStructures.jl/issues/2#issuecomment-1621949867_

Thanks @marcom. As I understand we need now to create a simple package `DSSP_Jll.jl` or something of the sort and register it, which will provide the interface for the binaries?

Same goes for the stride binary, correct?

**Comment by marcom** [comment]
Once the pull request gets merged in the Yggdrasil repo, everything should happen automatically and there should be a new package `DSSP_jll` in the general registry that we will be able to install like every other package or add to the Project.toml of this repo. In detail, the BinaryBuilder infrastructure runs the `build_tarballs.jl` for all platforms specified in the build script, and then automatically creates a new repo for the `_jll` package (example: https://github.com/JuliaBinaryWrappers/ViennaRNA_jll.jl) with the generated binary artifacts. This repo then gets automatically registered as a new package in the Julia registry.

Until the DSSP pull request gets merged, you can try it all out locally:

```
# In the following, I am assuming you are on linux.
# On another OS it should work in a similar way.

# Check out the pull request to the Yggdrasil repo
git clone https://github.com/marcom/Yggdrasil -b dssp pr-dssp
cd pr-dssp/D/DSSP

# Run the build_tarballs.jl script, see `build_tarballs.jl --help` for options.
# You can use `julia +1.9` or other versions, but `julia +1.7` is what BinaryBuilder repo runs at the moment AFAIK.
# Change the target platform `x86_64-linux-gnu-cxx11` to your target platform.
# If you don't specify a platform, all platforms will be built (takes some time).
# Info on the env vars is here: https://docs.binarybuilder.org/stable/environment_variables/
BINARYBUILDER_USE_CCACHE=false BINARYBUILDER_NPROC=1 \
    julia +1.7 ./build_tarballs.jl --verbose x86_64-linux-gnu-cxx11

# If you want to deploy to an installable julia package, use the --deploy argument.
# Use --deploy=local to install the package into ~/.julia/dev/
julia +1.7 ./build_tarballs.jl --verbose --deploy=local x86_64-linux-gnu-cxx11

# Now you can use this package locally from julia
using Pkg
Pkg.dev("~/.julia/dev/DSSP_jll.jl/")
```

**Comment by lmiq** [comment]
Oh, nice. It's even better. Let's wait then.

Do you think we are all convinced by the state of the STRIDE build and it's license?

**Comment by marcom** [comment]
To me the license issues sound ok, but I don't know how Mosè sees it. He might also just be busy at the moment preparing for JuliaCon.

Maybe also put the email from Dmitrij in the m3g/stride repo where he states that he grants usage under the MIT Expat license in the repo (perhaps under the docs dir).

What we could do in the meantime if we want to try everything out is:

- deploy the builds to github under our own usernames with `build_tarballs.jl --deploy=<username>/STRIDE_jll.jl`, and the same for DSSP. Best to build for all platforms, then it should work everywhere julia works.

- create a branch in this repo and start making the changes necesary to work with the jll packages, the packages can be added with `Pkg.add("https://github.com/username/STRIDE_jll.jl")`

But if it's not urgent it's easiest to wait for the BinaryBuilder pull requests to get merged.
