### ISSUE TITLE
interface with BioStructures

### ISSUE THREAD

**Issue by lmiq** [BioJulia/ProteinSecondaryStructures.jl#4]
It would be nice if one could directly call `dssp_run` and `stride_run` with a data structure from BioStructures directly.

That is fairly easy in the current state of the package, since the binaries are external programs that only read temporary PDB files. There are some details concerning the headers of the PDB files that both packages accept (or mmCIF files, for DSSP), and I have handled those (for PDB) in the current implementation. Something similar, or converting a structure to the PDBTools format before calling the `dssp_run(::Vector{PDBTools.Atom})` may be necessary (and similarly for `stride_run`). Trivial things, though.

The problem with supporting the BioStructures data is (from my first impression) that this is fairly huge dependency, for such a simple package. Thus, I would be willing to provide this functionality though a package extensions, such that it is only loaded if BioStructures is loaded separately.

**Comment by jgreener64** [comment]
You are correct that BioStructures is a large dependency. Now that package extensions are available I intend to move parts of it to extensions to remove the number of dependencies. I won't get round to it for a while though.

Having a package extension for it sounds good, or the code could go in BioStructures since ProteinSecondaryStructures is a fairly light dependency itself.

**Comment by lmiq** [comment]
It may become not so light if we manage to wrap SESCA as well to compute CD spectra. I think making the extensions is fine here. I'll work on that.

**Comment by jgreener64** [comment]
It is now possible to run DSSP and STRIDE on BioStructures objects and get the secondary structure code from within BioStructures: https://biojulia.dev/BioStructures.jl/stable/documentation/#Assigning-secondary-structure.

Other output of DSSP/STRIDE may be added in future.

**Comment by lmiq** [comment]
Cool. I guess we close this here, right? Or do you think there is an integration that can be useful still?

**Comment by jgreener64** [comment]
Yes probably close this one.
