### ISSUE TITLE
DSSP not working on on windows

### ISSUE THREAD

**Issue by lmiq** [BioJulia/ProteinSecondaryStructures.jl#8]
Needs to investigate if the underlying packages (dssp?) is generating different results on Windows, or if the parsing fails for some reason.

@marcom have you seeing anything like that before?

**Comment by lmiq** [comment]
I just had access to a Windows machine, and DSSP is indeed not working there. The package doesn't throw any error, but the secondary structure is returned as all-turns. 

Will investigate what's going on ASAP.

**Comment by marcom** [comment]
I just had a look at the build logs for windows in Yggdrasil but didn't see any compilation warnings there.

One difference that I can think of is that on 64-bit windows, `int` and `long` is 32 bits and `long long` is 64 bits, whereas on most other 64-bit systems including linux, `int` is 32 bits and `long` is 64 bits. But not sure if that is causing this problem, and the build has `-Wall -Wextra` warnings enabled.

**Comment by lmiq** [comment]
I've opened an issue upstream to see if they have any insight on this: https://github.com/PDB-REDO/dssp/issues/63

**Comment by lmiq** [comment]
Fixed by: https://github.com/JuliaPackaging/Yggdrasil/pull/7107
